name: Unit Tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        use-ipykernel: [false, true]
        python-env: ["py311", "py312", "py313", "py314"]
        zmq-encoding: ["json", "msgpack"]
        group: [1, 2, 3]
        exclude:
          - python-env: "py311"
            zmq-encoding: "msgpack"
          - python-env: "py312"
            zmq-encoding: "msgpack"
          - python-env: "py313"
            zmq-encoding: "msgpack"
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        # Need this to get version number from last tag
        fetch-depth: 0
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "7.x"
    - name: Install dependencies
      run: |
        pixi install --environment=${{ matrix.python-env }}
        pixi list --environment=${{ matrix.python-env }}
        pixi run --environment=${{ matrix.python-env }} pip list
        pixi run --environment=${{ matrix.python-env }} conda list

    - name: Test with pytest
      env:
        USE_IPYKERNEL: ${{ matrix.use-ipykernel }}
        USE_ZMQ_ENCODING: ${{ matrix.zmq-encoding }}
      run: |
        # pytest -k test_ip_kernel_func -vvv
        pixi run --environment=${{ matrix.python-env }} coverage run -m pytest -vv --splits 3 --group ${{ matrix.group }}
        pixi run --environment=${{ matrix.python-env }} coverage report -m
